### ISSUE TITLE
can't register

### ISSUE THREAD

**Issue by McLeopold** [spaceshipoperator/redshirts#1]
When I attempt to register, I'm taken to the login page with a "login failed" error message.  No data is inserted into the database.

**Comment by spaceshipoperator** [comment]
wow...I think  I need more information, not sure how you're getting a "login failed" message...registration is _very_ rudimentary at this point and there's not much that can happen to prevent a user from being created (that is inserted into the database).  It almost seems as if your app isn't connecting to your database...maybe you could confirm at the node repl?
