### ISSUE TITLE
error after login

### ISSUE THREAD

**Issue by McLeopold** [spaceshipoperator/redshirts#2]
I inserted data directly into the database for my user.  Then after login, I get the following error:

/home/scott/redshirts/db/index.js:176
        req.session.internships = result.rows;
                                 ^
TypeError: Cannot read property 'rows' of undefined
    at [object Object].callback (/home/scott/redshirts/db/index.js:176:34)
    at [object Object].handleError (/home/scott/redshirts/node_modules/pg/lib/query.js:87:10)
    at [object Object].<anonymous> (/home/scott/redshirts/node_modules/pg/lib/client.js:130:24)
    at [object Object].emit (events.js:64:17)
    at Socket.<anonymous> (/home/scott/redshirts/node_modules/pg/lib/connection.js:47:12)
    at Socket.emit (events.js:64:17)
    at Socket._onReadable (net.js:678:14)
    at IOWatcher.onReadable [as callback](net.js:177:10)

**Comment by spaceshipoperator** [comment]
yeah...you shouldn't have to manually insert data into the db, again makes me think you're not connecting to your local database....and I've given little attention to proper error handling (for shame!).

Have a look at the first couple of lines in https://github.com/spaceshipoperator/redshirts/blob/master/db/index.js

I know...that's funny place for a connection string

**Comment by McLeopold** [comment]
I am connected, because the login will succeed if I manual insert the data.  I created a database with the exact same user name, password and database so the connection string would be the same.  It appears that no data is written.  Are there any transactions or specific permissions the db user should have?

**Comment by spaceshipoperator** [comment]
all right Scott...you can review all the nasty commits (please pardon me), but I'm pretty sure the problem you hit was to do with me cookies bein' persistant and, as such, unacceptable by me browser...I don't fully unnerstand, but I switched it to session resident cookies and...I think its fixed, in this commit: https://github.com/spaceshipoperator/redshirts/commit/7ac4e4267f152a45f7c44c98517de28ed7bb9331

Thanks for bringing this up, averted some real pain in deployment
